# Generated by Django 5.2.17 on 2026-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="внешний идентификатор"
                    ),
                ),
                (
                    "user_id",
                    models.PositiveBigIntegerField(verbose_name="идентификатор пользователя"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email получателя")),
                ("subject", models.CharField(max_length=255, verbose_name="тема письма")),
                ("message", models.TextField(verbose_name="текст письма")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка отправки"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="отправлено")),
                (
                    "last_error",
                    models.CharField(blank=True, max_length=255, verbose_name="последняя ошибка"),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "indexes": [models.Index(fields=["status"], name="mailing_status_idx")],
            },
        ),
    ]
