# Generated by Django 5.2.17 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "рассылка", "verbose_name_plural": "рассылки"},
        ),
        migrations.AlterField(
            model_name="mailing",
            name="attempts",
            field=models.PositiveIntegerField(default=0, verbose_name="попыток отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True, verbose_name="токен обработчика"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="захвачено обработчиком"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создано"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email получателя"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="external_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="внешний идентификатор"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_error",
            field=models.CharField(blank=True, max_length=128, verbose_name="последняя ошибка"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.TextField(verbose_name="текст письма"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="отправлено"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("processing", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка отправки"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="тема письма"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="user_id",
            field=models.PositiveBigIntegerField(verbose_name="идентификатор пользователя"),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_id__gt", 0)), name="mailing_user_id_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_token__isnull", False),
                        ("claimed_at__isnull", False),
                        ("sent_at__isnull", True),
                        ("status", "processing"),
                    ),
                    models.Q(
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                        ("sent_at__isnull", False),
                        ("status", "sent"),
                    ),
                    models.Q(
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                        ("sent_at__isnull", True),
                        ("status__in", ("pending", "failed")),
                    ),
                    _connector="OR",
                ),
                name="mailing_status_fields_consistent",
            ),
        ),
    ]
