# Generated by Django 5.2.17 on 2026-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0002_alter_mailing_options_alter_mailing_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mailing",
            name="mailing_status_fields_consistent",
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="следующая попытка"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("retrying", "Ожидает повтора"),
                    ("processing", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка отправки"),
                ],
                default="pending",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(
                fields=["status", "next_attempt_at", "id"], name="mailing_ready_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status", "claimed_at", "id"], name="mailing_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_token__isnull", False),
                        ("claimed_at__isnull", False),
                        ("next_attempt_at__isnull", True),
                        ("sent_at__isnull", True),
                        ("status", "processing"),
                    ),
                    models.Q(
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                        ("next_attempt_at__isnull", True),
                        ("sent_at__isnull", False),
                        ("status", "sent"),
                    ),
                    models.Q(
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                        ("next_attempt_at__isnull", True),
                        ("sent_at__isnull", True),
                        ("status__in", ("pending", "failed")),
                    ),
                    models.Q(
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                        ("next_attempt_at__isnull", False),
                        ("sent_at__isnull", True),
                        ("status", "retrying"),
                    ),
                    _connector="OR",
                ),
                name="mailing_status_fields_consistent",
            ),
        ),
    ]
